### ISSUE TITLE
When loading the ember api viewer, I'm seeing issues with URLs

### ISSUE THREAD

**Issue by acorncom** [ember-learn/ember-api-docs#151]
I'm currently looking at the api viewer using the proxied url below:
http://ember-website.herokuapp.com/api-new

When doing so, I arrive on the page and then am redirected to:
http://ember-website.herokuapp.com/api-new/api-new/

Clicking any link results in errors, but if I then adjust the url to have a double `/api-new/api-new` things work again.  My understanding is the Fastboot app we're hitting has a `rootUrl` of `/api-new`, which may be the source of these problems ...

**Comment by sivakumar-kailasam** [comment]
@acorncom this is fixed with #155. 

If you wanna test this on your local,
- Run `npm run heroku-postbuild` & then `./bin/ember-fastboot tmp/deploy-dist --serve-assets-from tmp/deploy-dist` 
- Setup a nginx as mentioned in [this doc](https://gist.github.com/sivakumar-kailasam/ffc5d7609b60bd1ccc1cbe2297a9058e ) 
- Accessing http://localhost:8080/api-new/ would be loading the page through nginx & http://localhost:3000 will be the fastboot app


![standalone proxy together](https://cloud.githubusercontent.com/assets/604117/24049473/3309c594-0b52-11e7-8abb-afae74262d61.gif)

**Comment by acorncom** [comment]
Thanks @sivakumar-kailasam !
