### ISSUE TITLE
Download current project version's yet to be visited docs for offline viewing

### ISSUE THREAD

**Issue by sivakumar-kailasam** [ember-learn/ember-api-docs#207]
We mark our json-docs with `cache-control: 'max-age=365000000, immutable'`  header. This makes them available offline on fetch requests if they were accessed before on chrome & firefox. This is even without service workers setup on the page. 

On other browsers yet to implement immutable header, they'll be loaded from disk after a 304 confirmation.

To make the UX of viewing a particular version of the docs better, we want to start downloading the json-docs that the viewer is yet to visit in the background for priming the cache. It would be great if we can do this over a web worker using [ember-web-workers](https://github.com/yaymukund/ember-web-workers) since that'd make it non-blocking & has [great browser support](http://caniuse.com/#feat=webworkers)

**Comment by fpapado** [comment]
Hello!

Fresh off the EmberConf presentation, the syncing / caching / storage features of the new API docs sound like something I want to help with :)

# Design
I'm still going through the code & issues, but from what I understand:
- A core concept of fetching the docs is the manifest file that lists relevant resources for the current version
- This feature (web worker) should iterate though the list in the manifest and fetch the resources, such that they are placed in the cache
- These resources will then be handled either with immutable or 304 by the browser, whenever the user visits them

I infer between https://github.com/ember-learn/ember-api-docs/issues/134 and https://github.com/ember-learn/ember-api-docs/pull/144/commits/7311c05bf906704f93696db63667c7c189f342c5 that the current idea is to keep Service Worker as an offline cache layer, but defer the background loading requests to something more on the application side / web-worker; that's probably a good choice, given the still-spotty SW availability.
That latter PR link also has a nice basis for how to do the messaging (`postmessage` also exists in `ember-web-workers`).

# Next?
I haven't worked with web workers much, but I would like to give this a shot.
Do I have the main idea right? Is there any design or implementation consideration I'm missing?

(I also have an ember side-project on the PWA front, so I'm hoping to offer some ideas on service-worker caching, and see how it works when you factor in CDN and multiple resources. But that's for another issue!)

**Comment by toddjordan** [comment]
Excellent :heart: Thanks for your willingness to help!   We currently have a working service worker implementation using ember-service-worker, but still need to do what you mentioned (with workers, download the static json api files).  Our deployment setup is preventing the service worker implementation from working atm (our proxy/caching scheme is causing trouble), but you can certainly give it a shot and get it working locally.

**Comment by fpapado** [comment]
I have started working on this over at https://github.com/fpapado/ember-api-docs/commit/966dc07c7fd47b710fe4b34abacd0640de693dba.

# Progress
So far, I have managed to spin up a web worker via a client service, and am able to pass messages for the current project & version to it! Thus, the worker has the information it needs to make the requests (currently it logs them out). This took some small changes to `ember-service-workers` (some broccoli paths didn't resolve well), but was otherwise pretty straightforward.

# Up next
The next part to work out is the fact that web-workers do not share the main scripts, which need to be imported separately via `importScripts(...)`. *The main thing I need in the worker from the app modules is the adapter logic for revision ids / requests* (https://github.com/ember-learn/ember-api-docs/blob/master/app/adapters/application.js#L23).

1. Given that the web worker scripts exist outside the main `app/` directory, I need to think about how to resolve the app modules, which might mean dealing with broccoli. Could also draw inspiration from https://github.com/ember-cli/ember-cli/issues/1011; or,
2. There is also an argument in favour of duplicating or factoring out the adapter functionality.

I'll try (1) and (2) over the weekend and see how it looks. After we're able to make the requests in the web worker, we'll have to think about when to actually use them, and whether it should be a setting somewhere.

**Comment by sivakumar-kailasam** [comment]
At present the [revision index file](https://ead-sk.global.ssl.fastly.net/rev-index/ember-2.12.0.json) only contains a mapping of the file name, we can probably save the relative path to the files. This will reduce lookup logic in this app. We can pass the rev index document to the web worker so that it knows all the urls it has to visit. 

Since these docs are immutable, once fetched the client won't make requests for them again, so all the web-worker has to do is fetch those files once. The `afterModel` of project-version route may be a potential spot to invoke the web worker.

**Comment by fpapado** [comment]
Including the relative paths would definitely help a lot! Now that I think about it, even if that isn't possible, we could still pass the relevant url prefixes to the web-worker from the main thread.

Agreed on the requests process, the important thing is priming the cache for further lookups; the rest is handled by the browser / SW (immutable or 304 depending on features).

I'm currently calling the worker in the `redirect()` hook of project-version, I'll give `afterModel` a shot as well :)

**Comment by toddjordan** [comment]
Currently not actively working on an offline version.  We may pick this up in the future, but closing for now.
