### ISSUE TITLE
Array.includes docs duplicated

### ISSUE THREAD

**Issue by acorncom** [ember-learn/ember-api-docs#343]
Per @eccegordo in https://github.com/emberjs/website/issues/2991

> The same method seems to be duplicated in the docs output.

https://www.emberjs.com/api/ember/2.14/classes/Ember.MutableArray/methods/includes?anchor=includes

![Image of problem](https://user-images.githubusercontent.com/497659/30672425-2ac564f8-9e21-11e7-9b75-fcbd77715062.png)

**Comment by jenweber** [comment]
This is probably due to a logic error in `app/components/api-index-filter.js` in `filterMultipleInheritance` or something wrong with the use of `uniq`. If you console log `dedupedArray`, the duplicate is clear.

**Comment by akashdsouza** [comment]
This is because lodash's uniq method only accepts the array as an argument(https://github.com/lodash/lodash/blob/master/uniq.js#L20) and ignores the [rest](https://github.com/ember-learn/ember-api-docs/blob/master/app/components/api-index-filter.js#L41). Due to this, it only performs comparisons against the objects and returns the entire array as it is.
This can be overcome by using Ember's uniqBy method.

**Comment by akashdsouza** [comment]
This is because lodash's uniq method only accepts the array as an argument(https://github.com/lodash/lodash/blob/master/uniq.js#L20) and ignores the [rest](https://github.com/ember-learn/ember-api-docs/blob/master/app/components/api-index-filter.js#L41). Due to this, it only performs comparisons against the objects and returns the entire array as it is.
Ember uniqBy method can be used to overcome this. However, I'm not sure as to what should be the key for uniqBy. Perhaps, `file` ?

**Comment by toddjordan** [comment]
looks ok right now @jenweber @acorncom Fixed?
![image](https://user-images.githubusercontent.com/3609063/31506153-a59acedc-af44-11e7-809e-594b692e7775.png)

**Comment by jenweber** [comment]
Looks good to me. Closed.

**Comment by akashdsouza** [comment]
The issue looks like it is fixed with v2.16. However, lodash's uniq(used [here](https://github.com/ember-learn/ember-api-docs/blob/master/app/components/api-index-filter.js#L41)) doesn't do anything as it only accepts an [array as an argument](https://github.com/lodash/lodash/blob/master/uniq.js#L20).
