### ISSUE TITLE
DS.Snapshot is mentioned, but not documented

### ISSUE THREAD

**Issue by mike-north** [ember-learn/ember-api-docs#393]
Reported by @taoning2014 in a workshop

In several places (i.e., `DS.RESTAdapter`), there is mention of the `DS.Snapshot` type
<img width="624" alt="screen shot 2017-10-25 at 2 59 35 pm" src="https://user-images.githubusercontent.com/558005/32017598-33e45e92-b995-11e7-8e79-c1f1c9129e59.png">

If this is part of the ember-data public API, the type should be documented.

**Comment by acorncom** [comment]
@mike-north I don't disagree with the sentiment, but we're just the messengers here 😛  Would you mind opening an issue on https://github.com/emberjs/data to discuss?  Looks like we're honoring the `@private` here (https://github.com/emberjs/data/blob/4b419d91b3773a4b78412bd963ebbe16cb2423ff/addon/-private/system/snapshot.js#L14) which is why it isn't being show in the api docs ...  Thanks!

**Comment by toddjordan** [comment]
if you toggle "Show Private/Deprecated" in the left nav it will show up http://localhost:4200/ember-data/2.16/classes/DS.Snapshot , but the questions are 1. should it be public and/or 2. should it be linked to its reference in the public api.

**Comment by runspired** [comment]
I recently made Snapshot public, it will appear as so starting in 3.28

Historically, the data team has not wanted to make it public because importing/instantiating it is not a thing you can do. I added this caveat to the documentation before setting it to public.
