### ISSUE TITLE
Bring back "since" data

### ISSUE THREAD

**Issue by knownasilya** [ember-learn/ember-api-docs#425]
This data was available in the old API Docs, but has been removed in this new version. I think this is a very important feature for new and veteran Ember developers alike.

**Comment by toddjordan** [comment]
`since` is already available in the json response, so really this fix is just adding it to the class model and displaying in the template as part of the top data if it exists.  

In this area: 
![image](https://user-images.githubusercontent.com/3609063/34843726-49057060-f6dd-11e7-93dd-0aefbb67932b.png)

**Comment by toddjordan** [comment]
since is not getting properly set in the ember-jsonapi-docs repo.  until we fix that we can't merge the current PR.
