### ISSUE TITLE
opengraph tags for methods/events/properties should have more information

### ISSUE THREAD

**Issue by fivetanley** [ember-learn/ember-api-docs#47]
right now they don't show anything

![](https://dl.dropboxusercontent.com/s/o4vs3j069nca8ct/2016-06-01%20at%2011.09%20AM.png)

**Comment by mschinis** [comment]
picking this one up, I'm going to add additional meta tags using ember-cli-meta-tags.

**Comment by oskarrough** [comment]
@mschinis did you get going or maybe I can help?

I'd also like to remove the tomster open graph image. It takes up a lot of unnecessary vertical space as links are shared. We could replace with a little description, if that's useful.

**Comment by toddjordan** [comment]
@oskarrough go for it :-)

**Comment by oskarrough** [comment]
Alright! I looked at it and it seems meta tags are already setup, just a few missing things.

Are you OK with removing the tomster, too? Would be great to have a Slack chat with useful descriptions instead of the logo over and over again.

**Comment by sivakumar-kailasam** [comment]
I find the guides urls to be descriptive on slack. Can you please use that to cross verify? The logos themselves might not be the root cause for the lacking experience

**Comment by oskarrough** [comment]
Hey @sivakumar-kailasam, what do you mean by cross verifying the URLs? :)

I think what we have to do is 

1) make sure there are meta descriptions where possible
2) remove huge tomster logo

I agree that the logo isn't the root cause but it will nicer to share API links without it as it wastes 300px every time…

I noticed that the API returns descriptions filled with HTML. I'll make a helper to strip it out or do we have clean descriptions without markup? Example here in `data.attributes.description` https://ember-api-docs.global.ssl.fastly.net/json-docs/ember/3.2.0/classes/ember-3.2.0-ComputedProperty-a0c6b9793e.json

**Comment by sivakumar-kailasam** [comment]
I meant cross verify the  meta tag descriptors used on both pages :) You can probably add the helper to extract the text description.
