### ISSUE TITLE
Canonical URL broken for fastboot in prod

### ISSUE THREAD

**Issue by williamhaley** [ember-learn/ember-api-docs#491]
I noticed this in prod, and can re-create locally.

![prod canonical broken](https://user-images.githubusercontent.com/1851748/38764074-bc88afe2-3f6d-11e8-8c31-1e7bf1eac10d.png)

![canonical broken](https://user-images.githubusercontent.com/1851748/38764043-5e9497e8-3f6d-11e8-932f-5fe3d5cbc5df.png)

One can see the issue for any [non-release docs](view-source:https://emberjs.com/api/ember/2.18/classes/ArrayProxy). 

```
<link rel="canonical" href="http://[object Object]/ember/release/classes/ArrayProxy">
```

Seems like the issue is that fastboot's `request.host` is a computed property, and not a string.

I'm getting a PR together now.

**Comment by williamhaley** [comment]
@toddjordan Sorry, it looks like I only addressed part of the issue :-/

 Looks like the host is now `http://ember-api-docs.herokuapp.com/ember/release/modules/@ember%2Fobject`

Not sure how fastboot infers what the host should be. Maybe it's just better to hardcode to `emberjs.com` when using fastboot?

Or configure a whitelist like here? https://github.com/ember-fastboot/ember-cli-fastboot#host

**Comment by toddjordan** [comment]
yeah, I think for now a hardcode is fine, since we always want folks to come through emberjs.com/api

**Comment by williamhaley** [comment]
Will do :+1:

**Comment by williamhaley** [comment]
@toddjordan done

**Comment by toddjordan** [comment]
Thanks @williamhaley !  looks good.  This solves our problem for 2.16+,  now we need a function that converts pre-2.16 stuff to current (via https://github.com/ember-cli/ember-rfc176-data/blob/master/mappings.json) . Leaving this open until we get there.

**Comment by williamhaley** [comment]
@toddjordan Is there anything I can do to help with the pre-2.16 stuff? Seems like the Google voodoo is still kinda bad right now. A search for "Ember computed" yields the following. `2.15` docs are at the top with their broken `canonical` url. I'd love to help but I'm not sure where's best to look. No relevant recent docs show up (at all, as far as I can tell) in Google.

_Also, as an aside, the docs hosted at `www.emberjs.com.cn` seem to steal a lot of SEO away from "official" Ember docs. Does the Ember org own that? Is that a static mirror that can be shut down?_

<img width="633" alt="screen shot 2018-05-29 at 9 30 42 am" src="https://user-images.githubusercontent.com/1851748/40665505-fce5c970-6322-11e8-9fad-4bb3a84e0030.png">

**Comment by toddjordan** [comment]
Hi @williamhaley thanks for checking in.

We no longer have the explicit 2.15 redirect, so that's good.  In fact if you google specific computed functions, you might have better luck.  The problem is there isn't an equivalent to `Ember.Computed` that's navigable in post 2.15 API docs.  The closest we have is the `@ember/object` heading in packages, which shows those sub packages.  In fact, right now those old namepace urls are just readirecting to the landing page.

What I'd like to do is create pages for each sub-module that are similar to what we have for the top modules (like `@ember/object`). that way, it will play into our eventual (this year) plans for an expandable menu.  Let me know if you want to try to start tackling this.  I can point you in the right direction.

Unfortunately the Chinese ember site is not affiliated with us and am not sure we can make it go away other than crowding it out of the results.

**Comment by williamhaley** [comment]
> What I'd like to do is create pages for each sub-module that are similar to what we have for the top modules (like `@ember/object`). that way, it will play into our eventual (this year) plans for an expandable menu...

I love that idea. I was hoping that was somewhere on the roadmap and I feel like that would be easier for users to navigate and (fingers crossed) would help SEO visibility as well. 

I'd love to help out on that if I can. Please do point me in the starting direction and I'll try and do what I can. 👨‍💻
