### ISSUE TITLE
Where to browse @ember/object/computed functions?

### ISSUE THREAD

**Issue by ef4** [ember-learn/ember-api-docs#495]
I think [this page](https://www.emberjs.com/api/ember/3.1/modules/@ember%2Fobject%2Fcomputed) should be showing `alias`, `and`, `filter`, etc.

**Comment by toddjordan** [comment]
That menu item was due to a bug in the source documentation.  everything has been under `@ember/object`.  There's some enhancements planned that will make the subpackages fold, but not yet. https://github.com/emberjs/ember.js/pull/16502

I agree this bug makes it confusing... I'm tempted to hack in something hiding it until we get a patch ember release.
