### ISSUE TITLE
Dead links

### ISSUE THREAD

**Issue by robomalo** [ember-learn/ember-api-docs#513]
URL:
https://guides.emberjs.com/v2.17.0/object-model/enumerables/

"Ember.Enumerable API reference documentation." leads to https://emberjs.com/api/404

**Comment by toddjordan** [comment]
Thanks for reporting!  I see what's going on.  Will look to put a fix in this evening.

**Comment by toddjordan** [comment]
Couple of issues at play here... 
1. the source docs refer to it as Ember.Embedded and aren't reflecting the rfc 176 conversion.
2. The guides are referring to private docs.

I'm going to go ahead and put in a fix for item 1 and inquire about what to do on 2, (update guides or update visibility of class)

**Comment by knownasilya** [comment]
This page also has a dead enumerables link under 'Uses'. https://emberjs.com/api/ember/release/classes/EmberArray

**Comment by toddjordan** [comment]
Fixed in current release: https://guides.emberjs.com/release/object-model/enumerables/

Unfortunately guides updates for previous releases are a bit more challenging.  I'm going to close this because I think the answer is related to #520 in the fact that documentation that has disappeared from the current release breaks old "release" links.

Thanks for reporting
