### ISSUE TITLE
RSVP module missing in 3.1 and 3.2

### ISSUE THREAD

**Issue by Kilowhisky** [ember-learn/ember-api-docs#537]
RSVP module is still part of ember but not shown in the docs after version 3.0. 

Here is the link from 3.0.
https://www.emberjs.com/api/ember/3.0/modules/rsvp

**Comment by sivakumar-kailasam** [comment]
@toddjordan looks like rsvp got removed from the docs.

**Comment by toddjordan** [comment]
Known issue. We can do something to patch short term but real fix won’t be
seen until rsvp cuts a new release

**Comment by Kilowhisky** [comment]
Is there any workaround for all the docs that are missing then? Since the @ember changeover so much stuff is missing that the only way I’m able to find anything in the docs is that ive been using ember so long I know it’s still there somewhere. 

All the more junior devs that I direct to the docs end up thinking that I’m use magic private apis or end up doing some backwards way of doing things not realizing there is a framework method for it.

**Comment by sivakumar-kailasam** [comment]
https://github.com/tildeio/rsvp.js#basic-usage is probably the best source
until then

*Regards,*
Siva

**Comment by toddjordan** [comment]
ok, checked back in on this issue.  In the ember canary(master) branch, we get rsvp documentation:
![image](https://user-images.githubusercontent.com/3609063/49704204-09c4bd00-fbde-11e8-92f5-00d2124c4e33.png)

Problem is on the release(3.6) and beta(3.7) branches they don't because rsvp 4.8.2 is being installed into node modules instead of 4.8.4 (which has the good docs).  There doesn't seem to be a good reason that 4.8.4 doesn't exist in these releases, other than that the yarn lock file has its rsvp entries split: https://github.com/emberjs/ember.js/blob/beta/yarn.lock#L8451-L8459

PRing a fix to get the beta branch to grab 4.8.4 so we can get this back in the docs for 3.7

**Comment by toddjordan** [comment]
Fixed in current build.  Should get backported, but is difficult based on the issue being with ember source.  Not impossible, but will take us coming up with a strategy for updating ember release docs without cutting an actually release.
