### ISSUE TITLE
Bad link

### ISSUE THREAD

**Issue by archebyte** [ember-learn/ember-api-docs#552]
https://www.emberjs.com/api/ember-data/release/classes/Ember

The "Ember" link found on this page:
https://www.emberjs.com/api/ember-data/release/modules/ember-data

<img width="938" alt="screen shot 2018-09-22 at 11 33 44 am" src="https://user-images.githubusercontent.com/18292613/45920614-9c658380-be5b-11e8-9067-a128e10c984b.png">

**Comment by toddjordan** [comment]
Yep.  The link is brought in through ember-inflector, which is a third part library ember-data uses.  the yuidoc process essentially "assumes" that inflector falls under the ember-data module because no module(package) is given in that library.  Therefore since Ember is specified as a namespace for inflector, it shows up in the "classes" list (which shows both classes and namespaces).  

_in the case of ember-data_ the classes list is lacking actual classes and only showing namespaces. This is another issue that we need to open unrelated to this)_

The most reasonable fix would be to prevent the link from showing. since there are no static functions for Ember in ember-data.  Plus it would reduce confusion.  

The "easy" fix would be to just hack an if statement into `app/templates/project-version/modules/module.hbs` something along the lines of

```handlebars
  {{#if submodules}}
    <section>
      <h2>Submodules</h2>
      <ul class="spec-method-list">
        {{#each submodules as |module|}}
          <li>
            {{#if (not(and (eq model.name "ember-data") (eq module "Ember"))}}
            {{#link-to 'project-version.modules.module' module}}
              {{module}}
            {{/link-to}}
            {{/if}}
          </li>
        {{/each}}
      </ul>
    </section>
  {{/if}}
```
_(not sure if the truth helper syntax is correct.  would need to double-check)_

The harder but "right" way to fix would be to generally not display a namespace in the list if that namespace has no items to load.  Probably the best way to do this is to make an update to ember-jsonapi-docs repositiory when the json is getting generated.  It would require some advanced parsing during the building of module classes/namespaces to ensure that the namespace links would be valid.  The downside this solution is that this doesn't leave us with a good way to update previous releases, other than re-running all docs scripts from previous releases.


I'm ok with either fix.  Maybe optimally we can fix the "easy" hack way and circle back for the more complicated fix at a later date.
