### ISSUE TITLE
 Docs for Route don't open on 3.6 

### ISSUE THREAD

**Issue by mariogintili** [ember-learn/ember-api-docs#588]
A picture is worth more than a thousand words 😄 

![image](https://user-images.githubusercontent.com/3522106/50825555-367d0900-1331-11e9-8683-b1a912163e26.png)

**Comment by mansona** [comment]
@mariogintili I'm a little confused 😖 is this the link you're going to https://emberjs.com/api/ember/release/classes/Route ?

because that seems to work for me 🤔 

I have a sneaking suspicion that this is due to the release that is in the progress of coming out at the moment...

**Comment by locks** [comment]
I also cannot reproduce and think it was due to the release!

**Comment by mansona** [comment]
If it was because of the release, I'm curious as to what could have caused the inconsistency to put people in this odd state 🤔 I would imagine that if it's something in browser caches and some level of inconsistency, this could affect quite a few users. I guess it also depends on how long we have set the cache-control for these data files

**Comment by mariogintili** [comment]
opens now guys!

**Comment by mansona** [comment]
How do we feel about leaving this open as an issue to track "just after release some weird things happen"... 

Or will that just cause noise and not be helpful?

**Comment by toddjordan** [comment]
@mansona I'm gonna close bc we have ~70 issues I think this will rot and only contribute to noise.
