### ISSUE TITLE
Missing hasBlock template helper

### ISSUE THREAD

**Issue by ef4** [ember-learn/ember-api-docs#595]
I can't find the hasBlock template helper anywhere in the docs. AFAIK it's public API.

**Comment by kennethlarsen** [comment]
@ef4 There's a mention if it here: https://guides.emberjs.com/release/components/block-params/#toc_supporting-both-block-and-inline-component-usage-in-one-template

Is that sufficient?

**Comment by jenweber** [comment]
All Ember public api needs to be findable in the API docs directly, so it’s not enough to have a mention in the Guides.

If someone wants to help with this, the steps are:
1. In the Ember.js codebase, find the declaration of hasBlock.
2. See if it has an `@class` declaration in the file, as part of a YUIdoc code comment. If it does not, add one. See other template helpers for examples
3. See if the hasBlock Code comment is missing anything else that other helpers have, like `@public` or `@static`
4. If you have done this correctly, you should get a failing test due to the number of API docs changing. Update the count so it passes.
5. PR any changes to the Ember.js codebase and link to your PR here

**Comment by habdelra** [comment]
I can take this issue on.

**Comment by habdelra** [comment]
I think there are a bunch of helpers that are more foundational to glimmer, like `{{yield}}`, `{{with}}` where the documentation was just put in the `packages/@ember/-internals/glimmer/index.ts`, despite the real functionality living deeper below. This seems to fall into that bucket, which probably explains why the documentation is missing from the API docs. The clearest place where I could find where the `{{has-block}}` helper is handled is: https://github.com/emberjs/ember.js/blob/master/packages/%40ember/-internals/glimmer/lib/component-managers/curly.ts#L239-L242 But really, I think there are a lot of places that actually contribute to this functionality. Probably documenting `{{has-block}}` in the `packages/@ember/-internals/glimmer/index.ts` file is the easiest place to put it.

**Comment by mehulkar** [comment]
Where does this documentation end up showing up for a user? I looked around on emberjs.com but couldn’t find it, and couldn’t find a reference to @emberjs/-internals either.

**Comment by habdelra** [comment]
After this change is included in a released version of Ember it will show up here https://api.emberjs.com/ember/release/classes/Ember.Templates.helpers

**Comment by toddjordan** [comment]
fixed ❤️
