### ISSUE TITLE
http docs do not redirect to https

### ISSUE THREAD

**Issue by BryanCrotaz** [ember-learn/ember-api-docs#703]
**GENERAL**
```
Request URL: http://api.emberjs.com/ember-data/release
Request Method: GET
Status Code: 304 Not Modified
Remote Address: 151.101.62.217:80
Referrer Policy: no-referrer-when-downgrade
```

**RESPONSE HEADERS**
```
Accept-Ranges: bytes
Access-Control-Allow-Origin: *
Age: 18
Content-Encoding: gzip
Content-Length: 16276
Content-Type: text/html; charset=utf-8
Date: Thu, 16 Apr 2020 14:18:11 GMT
Etag: W/"ccde-snZZ26D/kHnWf7eDHDGVCM+TeCI"
Server: Cowboy
Vary: Accept-Encoding
Via: 1.1 varnish
X-Cache: HIT
X-Cache-Hits: 1
X-Served-By: cache-lhr7359-LHR
X-Timer: S1587046691.061907,VS0,VE1
```

**REQUEST HEADERS**
```
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Accept-Encoding: gzip, deflate
Accept-Language: en-GB,en-US;q=0.9,en;q=0.8
Cache-Control: max-age=0
Connection: keep-alive
Cookie: _ga=GA1.2.2040095810.1582575676; _gid=GA1.2.1994989037.1586955229; _gat=1
Host: api.emberjs.com
If-None-Match: W/"ccde-snZZ26D/kHnWf7eDHDGVCM+TeCI"
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36
```

**Comment by Gaurav0** [comment]
@sivakumar-kailasam Not sure how I broke this, but I must have. Can you have a look?

**Comment by sivakumar-kailasam** [comment]
This issue used to exist before. The fastboot server [enforces this](https://github.com/ember-learn/ember-api-docs/blob/master/bin/ember-fastboot#L40-L45) via [express-sslify](https://github.com/florianheinemann/express-sslify#reverse-proxies-heroku-nodejitsu-and-others). Looking at the code, I can't spot anything that might be have caused this. 

Another possible alternative we can try here is to configure this at fastly level instead of handling at the heroku level.

**Comment by amyrlam** [comment]
If we want to go the Fastly route... we are using an override host in Fastly: https://manage.fastly.com/configure/services/2BpcOzgZIMJBEri0R1AvY8/versions/6/settings (needs access, can pair) 

We'll need to figure out what's the best path if we want to use Force TLS, probably create a request setting instead of the override host option.
![image](https://user-images.githubusercontent.com/1372946/80555240-8fd4d580-8984-11ea-8e88-955a172c28aa.png)

From https://docs.fastly.com/en/guides/specifying-an-override-host#caveats-about-using-the-global-override-host

**Comment by Gaurav0** [comment]
I think we're going to have to; we already force https in heroku and it does redirect to https if you go directly to http://ember-api-docs-subdomain-setup.herokuapp.com but not if you go through the domain redirect from http://api.emberjs.com

**Comment by amyrlam** [comment]
cc @rwwagner90 

I will start documenting what I know about our https from Heroku to Fastly so can move forward on this. There will be a bit of spelunking on my end

**Comment by amyrlam** [comment]
Possible to sync on the issue at Thursday's meeting (I can be there), or plan another time when Siva is free? Wasn't sure if should ping on Discord now, I self set a Slack "snooze"

Left some notes in Notion to get started, since all the things are in Heroku / Fastly accounts. Notion is also account-protected though. https://www.notion.so/emberteam/Infra-cleanup-2ff5fb7a10654f6195f4d4223c2313e5

**Comment by rwwagner90** [comment]
@amyrlam @Gaurav0 @sivakumar-kailasam I think it probably makes sense to do a one off meeting to discuss this stuff. Perhaps sometime next week?

**Comment by amyrlam** [comment]
sounds good, am flexible, can meet on weekend too, let me know

**Comment by Gaurav0** [comment]
sounds good. Let me know when.

**Comment by sivakumar-kailasam** [comment]
I'm available to meet on the weekend as well.

Regards,
Siva

**Comment by Gaurav0** [comment]
Can we do 12pm EDT?

**Comment by amyrlam** [comment]
I can do 12pm Eastern (or later) Saturday or Sunday, let me know!

**Comment by rwwagner90** [comment]
12 Saturday should be fine with me. Can someone send out a meeting invite?

**Comment by sivakumar-kailasam** [comment]
I don't think there's too much I can do to help at this point since we really need fastly support or someone familiar with this sort of setup to help us validate & tweak our fastly config.


Here are few things that are good to know while having a conversation with them, 
- We can't remove fastly from this stack since our fastboot apps can't keep with the traffic we get. Our fastly sponsorship requires that we configure fastly as a service and not as an addon on heroku, so there's a bit of extra complexity added because of this.
- Fastboot can't identify if a request is over https/http since heroku [router terminates ssl](https://devcenter.heroku.com/articles/http-routing#routing). So we had set the http headers that enforce browsers to switch to https if they're on http. We tried setting this up with a middleware but it seems like those headers are missing in the responses.
1. For app redirects to work properly in a fastboot env, we'll need fastly to set the override header so that heroku can hand that info over to fastboot. 

I tried couple of configs to tweak the request settings on fastly to make it work as their documentation suggests, but that doesn't seem to work. So instead of meeting this week, @amyrlam please send a support request mail to fastly with me included in it & I can answer any questions that might come up in that conversation.

**Comment by amyrlam** [comment]
I have this half working, redirects to the https Heroku URL. Have a support ticket in to figure out the last step!

**Comment by amyrlam** [comment]
@BryanCrotaz this is solved with the Fastly setup now! Thanks @Gaurav0 @sivakumar-kailasam @rwwagner90 for bearing with me on this issue.

Please @ me if you see anything else and thanks for the report!
