### ISSUE TITLE
EmberObject API page redirects to 404 when on ember versions 3.12 or below

### ISSUE THREAD

**Issue by Mikek2252** [ember-learn/ember-api-docs#867]
When trying to navigate from `https://api.emberjs.com/ember/3.13/classes/EmberObject` to `3.12` or below( i have checked up to 3.0.0) through the drop down it takes you to a 404 page. 

Also if you trying to click the emberObject link here
![Screenshot 2023-06-07 at 12 13 33](https://github.com/ember-learn/ember-api-docs/assets/3742188/ee2fac3f-25d1-405d-be6f-a64e9f9874b4)
it also takes you to a 404 page

**Comment by EWhite613** [comment]
Happens in 3.16 as well. Majority of class links are broken

**Comment by mansona** [comment]
This has been fixed since the end of last week 🎉 

We recently updated the infrastructure of the ember-api-docs and even added some data validation to catch problems like this before they happen.

If you still notice there is an issue, please let us know and we can either reopen this issue or create a new one 👍
