### ISSUE TITLE
logo isn't working in the header in the redesign

### ISSUE THREAD

**Issue by mansona** [ember-learn/ember-api-docs#878]
on the redesign (example page: https://ember-api-do-website-re-9n6ekm.herokuapp.com/ember/release/classes/Application ) the logo isn't working. I'm not sure why it's not working because I thought it was supposed to be in the ember-styleguide and the header component is in the [ember-styleguide](https://github.com/ember-learn/ember-styleguide) 🤔 

![Image](https://github.com/ember-learn/ember-api-docs/assets/594890/79860bb6-0f34-4dac-b07a-150c771bcda9)

We need to investigate exactly what is broken here

**Comment by mansona** [comment]
@lukasnys said they would take a look at this one 👍

**Comment by lukasnys** [comment]
Did some searching and I assume it's because of fingerprinting. 

When running `ember-api-docs` locally, the logo shows up as expected. However on the preview app the `images/ember-logo.svg` src is changed to `/images/ember-logo-1620c0dd8cf2355672f04d433a09409d.svg`.

In `ember-styleguide` the fingerprint config is set to `['js', 'css', 'map']` so no `svg` files are fingerprinted in the addon. However, `svg` is part of the fingerprinted extensions in `ember-api-docs` so I guess the `src` is changed to a fingerprinted svg file that doesn't exist.

@mansona I'm not 100% familiar with fingerprinting so just wanted to do a sanity check with you if what I wrote above makes any sense at all. Would adding `svg` to the `ember-styleguide` fingerprinting config fix this do you think? Let me know if you would prefer to pick this up on Discord.
