### ISSUE TITLE
Namespace/Module Incosistencies

### ISSUE THREAD

**Issue by Gaurav0** [ember-learn/ember-api-docs#96]
References to namespaces that don't exist and other data issues break the app.

**Comment by toddjordan** [comment]
@Gaurav0 can you be specific about the "other data issues"?

**Comment by Gaurav0** [comment]
@toddjordan So far, the only "other" data issues I have directly found are references to private methods and properties from public ones.

However, the app should never break regardless of any data issue. A reference to a namespace, module, class, property, method, or event that either doesn't exist or isn't currently visible according to toggles should result in a friendly error message.

**Comment by toddjordan** [comment]
ok, in 2.10, I clicked on every namespace and module.  The only one that doesn't come up is the 'support' module.  in 2.9 the glimmer module shows headings but no data

**Comment by toddjordan** [comment]
Ok, I'm going to use this issue to highlight specific differences in content between the new api-docs and the currently deployed version.

**Comment by toddjordan** [comment]
- [ ] ember-* is missing from each module (except ember)
- [ ] ember-extension-support is "support" in the new app (and loads blank)

new: 
![image](https://cloud.githubusercontent.com/assets/3609063/20868868/90180a76-ba34-11e6-88de-ab5dfdbba8c4.png)

old:
![image](https://cloud.githubusercontent.com/assets/3609063/20868867/823e16b6-ba34-11e6-99bc-7cc8776562fb.png)

- [ ] `Ember.ApplicationInstance` and `Ember.Test` load as Namespaces in other namespace details when in actuality they are Classes

![image](https://cloud.githubusercontent.com/assets/3609063/20868915/7c6360b0-ba35-11e6-87f4-f5d64ea721d3.png)

**Comment by toddjordan** [comment]
oddly, things are showing up as namespaces in the data that don't seem to be namespaces:
![image](https://cloud.githubusercontent.com/assets/3609063/21156375/9b993d5a-c143-11e6-8f04-17d0ba49ec2e.png)

**Comment by toddjordan** [comment]
In addition, the current api docs at emberjs.com/api combine "Classes and Namespaces" for modules, and it is unclear to me atm how our docs generation code differentiates.

**Comment by toddjordan** [comment]
Ok, I think I understand somewhat what's happening.

1. modules in the left nav are defined from source code with `@module` or `@submodule`
2. the classes within a module are defined from any `@class` defined within a source file with the `@module` or `@submodule` label
3. the namespaces within a module are defined from any `@namespace` defined within a source file with the `@module` or `@submodule` label
4. the list of namespaces in the left nav are defined from source code with `@static` and `@class`

Where this gets us into trouble is something like `Ember.ApplicationInstance` is not listed `@static`, but it is listed as an `@namespace` for `Ember.ApplicationInstance.BootOptions`.  Therefore `Ember.ApplicationInstance` shows up as a namespace under `ember-application`, but there is no link to it as a namespace.  Question for this is, should classes listed as `@namespace` be `@static`?  If not, should they really be an `@namespace`?

Another example is `Ember` shows up as a class under `ember-metal` because it has a `@class`, but it isn't listed as a class because it has an `@static`.  the fix for this is not to list `@class` as a class for a module if it also has a `@static`
